inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'spec/supplejack_common/tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/supplejack_common/**'
