language: ruby
rvm:
  - 2.6.5

services:
  - redis-server

cache: bundler

bundler_args: --without production

sudo: false

before_install:
  - gem update bundler

jobs:
  include:

    - stage: test
      name: 'Rubocop'
      script:
        - bundle exec rubocop

    - stage: test
      name: 'Rspec'
      script:
        - bundle exec rspec

    - stage: test
      name: 'bundle audit'
      script:
        - gem install bundler-audit
        - bundle audit update
        - bundle audit check

