language: ruby
rvm:
  - 2.3.8
services:
  - redis-server
cache: bundler
bundler_args: --without production
sudo: false
script:
  - bundle exec rspec
  - bundle exec rubocop
before_install:
  gem update bundler
